# Site
repository: chrismaree/PersonalWebsite
favicon: Directory of your favicon (eg. images/favicon.png)(optional)

# Personal info
name: Chris Maree
title: Electrical Engineer & full stack developer. Into open source software, blockchain and decentralized finance.
email: christopher.maree@gmail.com
website: chrismaree.io

# Social links
twitter_username: https://twitter.com/ChrisMaree__
github_username:  https://github.com/chrismaree
linkedin_username: https://www.linkedin.com/in/christopher-maree-49463312b/

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profilePic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Chris and I am a full stack developer with interests in blockchain technology and decentralized finance. I've been involved in a bunch of different opensourced projects and startups, you can check them out below. 
  
  I originally studied electrical engineering but fell in love with crypto & blockchain in 2016. I'm currently doing my masters financial technology because I think that to be successful in the decentralized(open) finance movement one needed an understanding of the fundamental economics to have a maximum long term impact in the space.
  
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  I also like scuba diving, photography, electronic music and good food.
  

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
