# Site
repository: chrismaree/PersonalWebsite
favicon: images/favicon.png

# Personal info
name: Chris Maree
title: Electrical Engineer & full stack developer. Into open source software, Ethereum and decentralized finance.
email: christopher.maree@gmail.com
website: chrismaree.io

# Social links
twitter_username: https://twitter.com/ChrisMaree__
github_username:  https://github.com/chrismaree
linkedin_username: https://www.linkedin.com/in/christopher-maree-49463312b/
telegram_username: chris_maree

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profilePic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi 👋! I'm Chris and I am a full stack developer with interests in blockchain technology and decentralized finance. I've been involved in a bunch of different opensourced projects and startups, you can check them out below. 
    
  During my bachelors in electrical engineering I discovered blockchain and cryptocurrencies and was immediately sold on the potential they have to radically transform our society. When I started exploring the DeFi space I realized just how important it is to understand the fundamental economics and financial markets of the traditional world inorder to build a better decentralized financial system. To this end I'm currently doing my masters in financial technology which covers a wide range of relevant fields like blockchain, datascience, software engineering and financial markets topics.
 
  I see blockchain as a technology that empowers people for the first time to challenge the power structures that define our society at a protocol level.

  Oh and I also like scuba diving, photography, electronic music and good food 🤘🚀.  
  
# Projects Section
projects_title: Open Source Projects

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Hackathons, Papers and Other Projects
more_content: |
  *Luna*


# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
