# Site
repository: chrismaree/PersonalWebsite
favicon: images/favicon.png

# Personal info
name: Chris Maree
title: Full-stack tinkerer building in crypto, open source, and mechanism design. Driven to create.
email: christopher.maree at gmail.com
website: chrismaree.dev

# Social links
twitter_username: chrismaree_
github_username:  chrismaree
linkedin_username: christopher-maree-49463312b
telegram_username: IAmChrisMaree

# About Section
about_title: About me
about_profile_image: images/profilePic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Chris — a crypto-native builder since 2016, working at the edge of technology, design, and decentralized systems. My work spans full-stack engineering, mechanism design, and experiments in cryptographic coordination.

  Currently exploring the intersection of finance, computer science, and economics, pursuing innovative ideas that could transform how we build and value digital assets.

  Beyond code, I create art installations, fly drones, explore ocean depths, and seek out live music and culinary adventures. Finding balance through creativity is essential to my process.
  
# Projects Section
# projects_title: Open source projects

# Experience Section
experience_title: Work experience & startups #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: Other smaller projects & hackathons
# more_content: |
  
otherProjects_title: Open source projects, Hackathons & papers

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/modern-resume-theme

# GitHub Pages settings
# Default settings for local development - override with _config.custom.yml or _config.github.yml
baseurl: ""
url: "http://localhost:4000"

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-remote-theme
