# Site
repository: chrismaree/PersonalWebsite
favicon: images/favicon.png

# Personal info
name: Chris Maree
title: Electrical Engineer & full stack blockchain developer. Passionate about open source software, blockchain and decentralized finance.
email: christopher.maree at gmail.com
website: chrismaree.dev

# Social links
twitter_username: DeFiChris
github_username:  chrismaree
linkedin_username: christopher-maree-49463312b
telegram_username: chris_maree

# About Section
about_title: About me
about_profile_image: images/profilePic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi 👋! I'm Chris and I am a full stack developer with interests in blockchain technology and decentralized finance. I've been involved in a bunch of different opensource projects and startups, you can check them out below. 
    
  I see blockchain as a technology that empowers people for the first time to challenge the power structures that define our society at a protocol level.

  Oh and I also like scuba diving, photography, live music and good food 🤘🚀.
  
# Projects Section
projects_title: Open source projects

# Experience Section
experience_title: Work experience & startups #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: Other smaller projects & hackathons
# more_content: |
  
otherProjects_title: Other Notable projects, hackathons & papers

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
