[build]
  command = "bundle update --bundler && rm -f Gemfile.lock && bundle install && bundle exec jekyll build"
  publish = "_site/"

[build.environment]
  RUBY_VERSION = "2.7.5"

[[plugins]]
  package = "@netlify/plugin-ruby-bundler"