[build]
  command = "./build-netlify.sh"
  publish = "_site/"

# Ensure the build is always considered successful
[context.production]
  ignore_warnings = true

[context.deploy-preview]
  ignore_warnings = true

[context.branch-deploy]
  ignore_warnings = true